### PR TITLE
run test against Node 14, 16, 18

### LINKED ISSUE #162: Cannot running eslint with v1.18.0
#### Actions Env
Version: v1.18.0
ESLint Version: 6.14.16
Node Version: actions/setup-node@v2 with 12
Reviewdog Version: v0.14.1

#### Screenshot
image

image

### LINKED ISSUE #163: reviewdog parse error in Vue 3: failed to unmarshal rdjson (DiagnosticResult)
**System Information:** 
```
macOS Monterey 
Version 12.6
Macbook Pro (M1, 2020)
Chip Apple M1
```

**Software / Frameworks:**
```
Vue.js 3 with TypeScript
Node.js version v18.14.0

```

**reviewdog.yml**
```
name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: '-c .eslintrc.js src'

```

I am using the above `reviewdog.yml` file on Github Actions and `action-eslint@v1` keeps failing today with the following error:
```
Run reviewdog/action-eslint@v1
  with:
    github_token: ***
    reporter: github-pr-review
    eslint_flags: -c .eslintrc.js src
    level: error
    filter_mode: added
    fail_on_error: false
    workdir: .
    tool_name: eslint
Run $GITHUB_ACTION_PATH/script.sh
  $GITHUB_ACTION_PATH/script.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    REVIEWDOG_VERSION: v0.1[4](https://github.com/xxx/actions/runs/xx021642/jobs/xxx#step:5:4).1
    INPUT_GITHUB_TOKEN: ***
    INPUT_LEVEL: error
    INPUT_REPORTER: github-pr-review
    INPUT_FILTER_MODE: added
    INPUT_FAIL_ON_ERROR: false
    INPUT_REVIEWDOG_FLAGS: 
    INPUT_ESLINT_FLAGS: -c .eslintrc.js src
    INPUT_WORKDIR: .
    INPUT_TOOL_NAME: eslint
    NODE_OPTIONS: 
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
[6](https://github.com/xxx/actions/runs/xxx/jobs/xxx#step:5:6).14.1[8](https://github.com/YPBConnectPlatform/connect-next-frontend/actions/runs/4249021642/jobs/7388780998#step:5:8)
eslint version:6.[14](https://github.com/xxx/actions/runs/xxx/jobs/xxx#step:5:15).[18](https://github.com/xxx/actions/runs/4249021642/jobs/xxxss#step:5:19)
 Running eslint with reviewdog 🐶 ...
  /bin/sh: 1: .eslintrc.js: not found
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token 
Error: Process completed with exit code 1.
```
I already have an .eslintrc.js file in the root of Vue 3 project. `reviewdog` was working fine but this issue just happened today. 
Is there any fix for this issue?

### PR DESCRIPTION
**Pull request by yshrsmz**
fix #163 
fix #162 

Run test against LTS versions and ensure compatibility.

### CODE REVIEW

File: script.sh [hunk 1]
```diff
@@ -11,7 +11,7 @@ echo '::group::🐶 Installing reviewdog ... https://github.com/reviewdog/review
 curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b "${TEMP_PATH}" "${REVIEWDOG_VERSION}" 2>&1
 echo '::endgroup::'
 
-npx --offline eslint --version
+npx --no-install -c 'eslint --version'
```
Comment (yshrsmz) [inline script.sh:14]: Node 14.21.3 comes with npm 6.14.8, and it [uses libnpx 10.2.4](https://github.com/npm/cli/blob/v6.14.18/package.json#L83)

Older npx seems not to support `--offline` option and the parsing logic of arguments is different from the latest version.

https://github.com/npm/npx/tree/v10.2.4
https://docs.npmjs.com/cli/v9/commands/npx

So to maintain the compatibility I switched to deprecated `--no-install` option and `-c` option.

**Comment by yshrsmz** [comment]
Does anyone have any comment on this?
I'm going to merge this tomorrow if there isn't one.
